// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChallengeStatus } from "./ChallengeStatus";

export type RunningChallenge = { _id: string, status: ChallengeStatus, hostname: string | null, ip: string | null, expires_at: string, name: string, slug: string, };
