// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChallengesUpdate } from "./ChallengesUpdate";
import type { VpnState } from "./VpnState";

export type ServerMessage = { "type": "challenges-update" } & ChallengesUpdate | { "type": "vpn-state" } & VpnState;
