[package]
name = "pod_assassin"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
config = "0.15.15"
dotenvy = "0.15.7"
futures = "0.3.31"
k8s-openapi = { version = "0.26.0", features = ["latest", "schemars"] }
kube = { version = "2.0.0", features = ["runtime", "derive"] }
serde = "1.0.219"
strum = { version = "0.27.2", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
toml = "0.9.5"
tracing = "0.1.41"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.19", features = [
    "chrono",
    "json",
    "env-filter",
    "local-time",
    "serde",
    "serde_json",
    "time",
] }
