[package]
name = "manifests"
version = "0.1.0"
edition = "2024"

[features]
utoipa = ["dep:utoipa"]
schemars = ["dep:schemars"]

[dependencies]
schemars = { version = "1.0.4", features = ["derive", "preserve_order"], optional = true }
serde = { version = "1.0.219", features = ["derive"] }
utoipa = { version = "5.4.0", features = ["chrono"], optional = true }
