[package]
name = "server"
version = "2.0.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
axum = { version = "0.8.4", features = ["macros", "ws"] }
axum-oidc = { git = "https://github.com/pfzetto/axum-oidc.git", rev = "65cb17560304ab31d342ebdb37db6cf4ed3aae99" }
axum-valid = "0.24.0"
chrono = { version = "0.4.42", features = ["serde"] }
clap = { version = "4.5.47", features = ["derive"] }
color-eyre = "0.6.5"
config = "0.15.11"
dashmap = "6.1.0"
derive_builder = "0.20.2"
dotenvy = "0.15.7"
exterminator = { version = "0.1.0", path = "../exterminator" }
fred = { version = "10.1.0", features = [
    "partial-tracing",
    "serde-json",
    "replicas",
    "enable-rustls-ring",
    "subscriber-client",
] }
futures = "0.3.31"
headscale = { version = "2.0.0", path = "../headscale" }
headscale_common = { version = "0.1.0", path = "../headscale_common" }
http = "1.3.1"
http-serde-ext = "1.0.2"
k8s-openapi = { version = "0.26.0", features = ["latest", "schemars"] }
kube = { version = "2.0.0", features = ["runtime", "derive"] }
manifests = { version = "0.1.0", path = "../manifests", features = [
    "schemars",
    "utoipa",
    "validator",
] }
mongo_utils = { version = "0.1.0", path = "../mongo_utils" }
mongodb = "3.2.3"
names = { version = "0.14.0", default-features = false }
openidconnect = { version = "4.0.0", default-features = false, features = [
    "reqwest",
    "rustls-tls",
    "timing-resistant-secret-traits",
] }
partial_struct = "0.4.5"
paste = "1.0.15"
rand = { version = "0.9.1", features = ["thread_rng"] }
reqwest = { version = "0.12.15", features = [
    "rustls-tls",
    "http2",
    "charset",
], default-features = false }
schemars = { version = "1.0.4", features = ["derive", "preserve_order"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10.9"
strum = { version = "0.27.1", features = ["derive"] }
tokio = { version = "1.45.0", features = ["full"] }
toml = "0.8.22"
tower = { version = "0.5.2", features = ["full", "tokio", "log"] }
tower-http = { version = "0.6.6", features = ["trace"] }
tower-sessions = "0.14.0"
tower-sessions-redis-store = "0.16.0"
tracing = "0.1.41"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.19", features = [
    "chrono",
    "json",
    "env-filter",
    "local-time",
    "serde",
    "serde_json",
    "time",
] }
ts-rs = { version = "11.0.1", features = ["chrono-impl", "bson-uuid-impl"] }
utoipa = { version = "5.3.1", features = ["axum_extras", "chrono"] }
utoipa-axum = "0.2.0"
utoipa-rapidoc = { version = "6.0.0", features = ["axum"] }
utoipa-redoc = { version = "6.0.0", features = ["axum"] }
utoipa-scalar = { version = "0.3.0", features = ["axum"] }
validator = { version = "0.20.0", features = ["derive"] }
visible = "0.0.1"
rustls = { version = "0.23.31", features = ["aws-lc-rs"] }
