/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthCheckSuccess {
    #[serde(rename = "success")]
    pub success: bool,
}

impl AuthCheckSuccess {
    pub fn new(success: bool) -> AuthCheckSuccess {
        AuthCheckSuccess {
            success,
        }
    }
}

