/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChallengeFlagMetaOneOf1 {
    /// Where the flag should be mounted inside the container
    #[serde(rename = "mount_path")]
    pub mount_path: String,
    /// File permissions for the flag file, in octal format (e.g. 644, defaults to 600)
    #[serde(rename = "permissions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Option<String>>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ChallengeFlagMetaOneOf1 {
    pub fn new(mount_path: String, r#type: Type) -> ChallengeFlagMetaOneOf1 {
        ChallengeFlagMetaOneOf1 {
            mount_path,
            permissions: None,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "dynamic-mount")]
    DynamicMount,
}

impl Default for Type {
    fn default() -> Type {
        Self::DynamicMount
    }
}

