/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChallengeContainer {
    #[serde(rename = "args", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub args: Option<Option<Vec<String>>>,
    #[serde(rename = "command", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub command: Option<Option<Vec<String>>>,
    #[serde(rename = "image")]
    pub image: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl ChallengeContainer {
    pub fn new(image: String, name: String) -> ChallengeContainer {
        ChallengeContainer {
            args: None,
            command: None,
            image,
            name,
        }
    }
}

