/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChallengeSpecOneOf : A fully static challenge with one answer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChallengeSpecOneOf {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ChallengeSpecOneOf {
    /// A fully static challenge with one answer
    pub fn new(r#type: Type) -> ChallengeSpecOneOf {
        ChallengeSpecOneOf {
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "static")]
    Static,
}

impl Default for Type {
    fn default() -> Type {
        Self::Static
    }
}

