/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChallengeMetadata {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Containers that should be created in the challenge Pod
    #[serde(rename = "containers")]
    pub containers: Vec<models::ChallengeContainer>,
    /// A short description, Markdown not supported
    #[serde(rename = "description")]
    pub description: String,
    /// Markdown description of the challenge
    #[serde(rename = "details")]
    pub details: String,
    #[serde(rename = "flags")]
    pub flags: Vec<models::ChallengeFlag>,
    /// A short unique name for the challenge
    #[serde(rename = "name")]
    pub name: String,
    /// A URL-friendly unique identifier for the challenge
    #[serde(rename = "slug")]
    pub slug: String,
}

impl ChallengeMetadata {
    pub fn new(r#type: Type, containers: Vec<models::ChallengeContainer>, description: String, details: String, flags: Vec<models::ChallengeFlag>, name: String, slug: String) -> ChallengeMetadata {
        ChallengeMetadata {
            r#type,
            containers,
            description,
            details,
            flags,
            name,
            slug,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "container")]
    Container,
}

impl Default for Type {
    fn default() -> Type {
        Self::Container
    }
}

