/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChallengeFlagMeta {
    ChallengeFlagMetaOneOf(Box<models::ChallengeFlagMetaOneOf>),
    ChallengeFlagMetaOneOf1(Box<models::ChallengeFlagMetaOneOf1>),
}

impl Default for ChallengeFlagMeta {
    fn default() -> Self {
        Self::ChallengeFlagMetaOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "static")]
    Static,
    #[serde(rename = "dynamic-mount")]
    DynamicMount,
}

impl Default for Type {
    fn default() -> Type {
        Self::Static
    }
}

