/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Challenge {
    /// A short description, Markdown not supported
    #[serde(rename = "description")]
    pub description: String,
    /// Markdown description of the challenge
    #[serde(rename = "details")]
    pub details: String,
    #[serde(rename = "flags")]
    pub flags: Vec<models::ChallengeFlag>,
    /// A short name for the challenge
    #[serde(rename = "name")]
    pub name: String,
    /// A URL-friendly unique identifier for the challenge
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "spec")]
    pub spec: Box<models::ChallengeSpec>,
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "ref")]
    pub r#ref: String,
}

impl Challenge {
    pub fn new(description: String, details: String, flags: Vec<models::ChallengeFlag>, name: String, slug: String, spec: models::ChallengeSpec, _id: String, r#ref: String) -> Challenge {
        Challenge {
            description,
            details,
            flags,
            name,
            slug,
            spec: Box::new(spec),
            _id,
            r#ref,
        }
    }
}

