/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChallengeSpec {
    ChallengeSpecOneOf(Box<models::ChallengeSpecOneOf>),
    ChallengeSpecOneOf1(Box<models::ChallengeSpecOneOf1>),
    ChallengeSpecOneOf2(Box<models::ChallengeSpecOneOf2>),
}

impl Default for ChallengeSpec {
    fn default() -> Self {
        Self::ChallengeSpecOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "static")]
    Static,
    #[serde(rename = "dynamic")]
    Dynamic,
    #[serde(rename = "container")]
    Container,
}

impl Default for Type {
    fn default() -> Type {
        Self::Static
    }
}

