/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChallengeFlagMetaOneOf {
    /// The static flag for the challenge
    #[serde(rename = "flag")]
    pub flag: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ChallengeFlagMetaOneOf {
    pub fn new(flag: String, r#type: Type) -> ChallengeFlagMetaOneOf {
        ChallengeFlagMetaOneOf {
            flag,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "static")]
    Static,
}

impl Default for Type {
    fn default() -> Type {
        Self::Static
    }
}

