/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChallengeFlag {
    /// A short description where the flag can be found. Visible only after solving the challenge.
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// Slug that will allow this flag to be referenced in contests
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "spec")]
    pub spec: Box<models::ChallengeFlagMeta>,
}

impl ChallengeFlag {
    pub fn new(slug: String, spec: models::ChallengeFlagMeta) -> ChallengeFlag {
        ChallengeFlag {
            description: None,
            slug,
            spec: Box::new(spec),
        }
    }
}

