/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChallengeSpecOneOf1 : A challenge with a custom validator
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChallengeSpecOneOf1 {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ChallengeSpecOneOf1 {
    /// A challenge with a custom validator
    pub fn new(r#type: Type) -> ChallengeSpecOneOf1 {
        ChallengeSpecOneOf1 {
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "dynamic")]
    Dynamic,
}

impl Default for Type {
    fn default() -> Type {
        Self::Dynamic
    }
}

