/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectionHintOneOf3 {
    #[serde(rename = "port")]
    pub port: i32,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ConnectionHintOneOf3 {
    pub fn new(port: i32, r#type: Type) -> ConnectionHintOneOf3 {
        ConnectionHintOneOf3 {
            port,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "udp")]
    Udp,
}

impl Default for Type {
    fn default() -> Type {
        Self::Udp
    }
}

