/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConnectionHint {
    ConnectionHintOneOf(Box<models::ConnectionHintOneOf>),
    ConnectionHintOneOf1(Box<models::ConnectionHintOneOf1>),
    ConnectionHintOneOf2(Box<models::ConnectionHintOneOf2>),
    ConnectionHintOneOf3(Box<models::ConnectionHintOneOf3>),
}

impl Default for ConnectionHint {
    fn default() -> Self {
        Self::ConnectionHintOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "ssh")]
    Ssh,
    #[serde(rename = "http")]
    Http,
    #[serde(rename = "tcp")]
    Tcp,
    #[serde(rename = "udp")]
    Udp,
}

impl Default for Type {
    fn default() -> Type {
        Self::Ssh
    }
}

