/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectionHintOneOf1 {
    #[serde(rename = "port")]
    pub port: i32,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ConnectionHintOneOf1 {
    pub fn new(port: i32, r#type: Type) -> ConnectionHintOneOf1 {
        ConnectionHintOneOf1 {
            port,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "http")]
    Http,
}

impl Default for Type {
    fn default() -> Type {
        Self::Http
    }
}

