/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CourseMetadataCourseItemStringItemsInner : # Generics:  - `Ref`: The type used to reference lessons and challenges
/// # Generics:  - `Ref`: The type used to reference lessons and challenges
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CourseMetadataCourseItemStringItemsInner {
    CourseMetadataCourseItemStringItemsInnerOneOf(Box<models::CourseMetadataCourseItemStringItemsInnerOneOf>),
    CourseMetadataCourseItemStringItemsInnerOneOf1(Box<models::CourseMetadataCourseItemStringItemsInnerOneOf1>),
}

impl Default for CourseMetadataCourseItemStringItemsInner {
    fn default() -> Self {
        Self::CourseMetadataCourseItemStringItemsInnerOneOf(Default::default())
    }
}

