/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CourseMetadataDetailedCourseItemItemsInnerOneOf1 {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl CourseMetadataDetailedCourseItemItemsInnerOneOf1 {
    pub fn new(_id: String, name: String, slug: String, r#type: Type) -> CourseMetadataDetailedCourseItemItemsInnerOneOf1 {
        CourseMetadataDetailedCourseItemItemsInnerOneOf1 {
            _id,
            name,
            slug,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "challenge")]
    Challenge,
}

impl Default for Type {
    fn default() -> Type {
        Self::Challenge
    }
}

