/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CourseItemType {
    #[serde(rename = "lesson")]
    Lesson,
    #[serde(rename = "challenge")]
    Challenge,

}

impl std::fmt::Display for CourseItemType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Lesson => write!(f, "lesson"),
            Self::Challenge => write!(f, "challenge"),
        }
    }
}

impl Default for CourseItemType {
    fn default() -> CourseItemType {
        Self::Lesson
    }
}

