/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CourseMetadata {
    /// A short description of the course
    #[serde(rename = "description")]
    pub description: String,
    /// The difficulty level of the course
    #[serde(rename = "difficulty")]
    pub difficulty: models::CourseDifficulty,
    /// A short unique name for the course
    #[serde(rename = "name")]
    pub name: String,
    /// A list of learning objectives for the course
    #[serde(rename = "objectives", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub objectives: Option<Option<Vec<String>>>,
    /// A list of course slugs that are prerequisites for this course
    #[serde(rename = "prerequisites", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub prerequisites: Option<Option<Vec<String>>>,
    /// A URL-friendly unique identifier for the course
    #[serde(rename = "slug")]
    pub slug: String,
    /// Tags associated with the course
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<Vec<String>>>,
}

impl CourseMetadata {
    pub fn new(description: String, difficulty: models::CourseDifficulty, name: String, slug: String) -> CourseMetadata {
        CourseMetadata {
            description,
            difficulty,
            name,
            objectives: None,
            prerequisites: None,
            slug,
            tags: None,
        }
    }
}

