/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CourseMetadataCourseItemStringItemsInnerOneOf1 {
    #[serde(rename = "challenge")]
    pub challenge: String,
}

impl CourseMetadataCourseItemStringItemsInnerOneOf1 {
    pub fn new(challenge: String) -> CourseMetadataCourseItemStringItemsInnerOneOf1 {
        CourseMetadataCourseItemStringItemsInnerOneOf1 {
            challenge,
        }
    }
}

