/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CourseMetadataDetailedCourseItemItemsInner {
    CourseMetadataDetailedCourseItemItemsInnerOneOf(Box<models::CourseMetadataDetailedCourseItemItemsInnerOneOf>),
    CourseMetadataDetailedCourseItemItemsInnerOneOf1(Box<models::CourseMetadataDetailedCourseItemItemsInnerOneOf1>),
}

impl Default for CourseMetadataDetailedCourseItemItemsInner {
    fn default() -> Self {
        Self::CourseMetadataDetailedCourseItemItemsInnerOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "lesson")]
    Lesson,
    #[serde(rename = "challenge")]
    Challenge,
}

impl Default for Type {
    fn default() -> Type {
        Self::Lesson
    }
}

