/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Course {
    /// A short description of the course
    #[serde(rename = "description")]
    pub description: String,
    /// The difficulty level of the course
    #[serde(rename = "difficulty")]
    pub difficulty: models::CourseDifficulty,
    /// A short unique name for the course
    #[serde(rename = "name")]
    pub name: String,
    /// A list of learning objectives for the course
    #[serde(rename = "objectives")]
    pub objectives: Vec<String>,
    /// A list of course slugs that are prerequisites for this course
    #[serde(rename = "prerequisites", skip_serializing_if = "Option::is_none")]
    pub prerequisites: Option<Vec<String>>,
    /// A URL-friendly unique identifier for the course
    #[serde(rename = "slug")]
    pub slug: String,
    /// Tags associated with the course
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "ref")]
    pub r#ref: String,
}

impl Course {
    pub fn new(description: String, difficulty: models::CourseDifficulty, name: String, objectives: Vec<String>, slug: String, _id: String, r#ref: String) -> Course {
        Course {
            description,
            difficulty,
            name,
            objectives,
            prerequisites: None,
            slug,
            tags: None,
            _id,
            r#ref,
        }
    }
}

