/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DetailedCourseChallenge {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
}

impl DetailedCourseChallenge {
    pub fn new(_id: String, name: String, slug: String) -> DetailedCourseChallenge {
        DetailedCourseChallenge {
            _id,
            name,
            slug,
        }
    }
}

