/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Lesson {
    /// A short name for the lesson
    #[serde(rename = "name")]
    pub name: String,
    /// A URL-friendly unique identifier for the lesson
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "attachments")]
    pub attachments: Vec<String>,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "course_slug")]
    pub course_slug: String,
}

impl Lesson {
    pub fn new(name: String, slug: String, _id: String, attachments: Vec<String>, content: String, course_slug: String) -> Lesson {
        Lesson {
            name,
            slug,
            _id,
            attachments,
            content,
            course_slug,
        }
    }
}

