/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LessonMetadata {
    /// A short name for the lesson
    #[serde(rename = "name")]
    pub name: String,
    /// A URL-friendly unique identifier for the lesson
    #[serde(rename = "slug")]
    pub slug: String,
}

impl LessonMetadata {
    pub fn new(name: String, slug: String) -> LessonMetadata {
        LessonMetadata {
            name,
            slug,
        }
    }
}

