/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotFoundError {
    #[serde(rename = "error")]
    pub error: String,
}

impl NotFoundError {
    pub fn new(error: String) -> NotFoundError {
        NotFoundError {
            error,
        }
    }
}

