/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCourseRequest {
    #[serde(rename = "metadata")]
    pub metadata: Box<models::CourseMetadata>,
    #[serde(rename = "ref")]
    pub r#ref: String,
}

impl UpdateCourseRequest {
    pub fn new(metadata: models::CourseMetadata, r#ref: String) -> UpdateCourseRequest {
        UpdateCourseRequest {
            metadata: Box::new(metadata),
            r#ref,
        }
    }
}

