/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateLessonRequest {
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "metadata")]
    pub metadata: Box<models::LessonMetadata>,
    #[serde(rename = "order")]
    pub order: i32,
}

impl UpdateLessonRequest {
    pub fn new(content: String, metadata: models::LessonMetadata, order: i32) -> UpdateLessonRequest {
        UpdateLessonRequest {
            content,
            metadata: Box::new(metadata),
            order,
        }
    }
}

