/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check system auth
         * @description Checks if your API key is valid
         *
         *     This endpoint is only avaliable to users authenticating with a system-wide API key
         */
        get: operations["check_system_auth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/challenges/{challenge_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get challenge */
        get: operations["get_challenge"];
        /**
         * Update challenge
         * @description If challenge is not found, it will be created
         */
        put: operations["update_challenge"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/challenges/{challenge_slug}/extend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extend a challenge
         * @description This endpoint adds more time to a challenge instance.
         */
        post: operations["extend_challenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/challenges/{challenge_slug}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a challenge */
        post: operations["start_challenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/challenges/{challenge_slug}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop a challenge */
        post: operations["stop_challenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/challenges/{challenge_slug}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a flag
         * @description Submits a flag for the specified challenge. If all correct flags have been submitted, the challenge instance will be stopped.
         */
        post: operations["submit_flag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all courses */
        get: operations["get_courses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get course */
        get: operations["get_course"];
        /**
         * Update course
         * @description If course is not found, it will be created
         */
        put: operations["update_course"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_slug}/last": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save last viewed item
         * @description Saves the last viewed lesson or challenge in the specified course
         */
        put: operations["save_last"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_slug}/lessons/{lesson_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get lesson */
        get: operations["get_course_lesson"];
        /**
         * Update lesson
         * @description If lesson is not found, it will be created
         */
        put: operations["update_course_lesson"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check server health
         * @description This endpoint returns `ok`
         */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Log in */
        get: operations["log_in"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Challenge schema
         * @description This endpoint returns JSON schema for the challenge manifest.
         */
        get: operations["get_challenge_schema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/contest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Contest schema
         * @description This endpoint returns JSON schema for the contest manifest.
         */
        get: operations["get_contest_schema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/contest-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Batch schema
         * @description This endpoint returns JSON schema for the contest batch manifest.
         */
        get: operations["get_contest_batch_schema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/course": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Course schema
         * @description This endpoint returns JSON schema for the course manifest.
         */
        get: operations["get_course_schema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/lesson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lesson schema
         * @description This endpoint returns JSON schema for the lesson manifest.
         */
        get: operations["get_lesson_schema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user details */
        get: operations["get_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket
         * @description Sends real-time updates about challenges and other events.
         */
        get: operations["websocket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthCheckSuccess: {
            success: boolean;
        };
        Challenge: components["schemas"]["ChallengeMetadata"] & {
            _id: string;
            ref: string;
        };
        ChallengeContainer: {
            args?: string[] | null;
            command?: string[] | null;
            image: string;
            name: string;
        };
        ChallengeFlag: {
            /** @description A short description where the flag can be found.
             *     Visible only after solving the challenge. */
            description?: string | null;
            /** @description Slug that will allow this flag to be referenced in contests */
            slug: string;
            spec: components["schemas"]["ChallengeFlagMeta"];
        };
        ChallengeFlagMeta: {
            /** @description The static flag for the challenge */
            flag: string;
            /** @enum {string} */
            type: "static";
        } | {
            /** @description To which container the flag should be mounted (if not provided, will be mounted to all containers) */
            container?: string | null;
            /** @description Where the flag should be mounted inside the container */
            mount_path: string;
            /** @description File permissions for the flag file, in octal format (e.g. 644, defaults to 600) */
            permissions?: string | null;
            /** @enum {string} */
            type: "dynamic-mount";
        };
        ChallengeMetadata: {
            /** @description A short description, Markdown not supported */
            description: string;
            /** @description Markdown description of the challenge */
            details: string;
            flags: components["schemas"]["ChallengeFlag"][];
            /** @description A short name for the challenge */
            name: string;
            /** @description A URL-friendly unique identifier for the challenge */
            slug: string;
            spec: components["schemas"]["ChallengeSpec"];
        };
        ChallengeSpec: {
            /** @enum {string} */
            type: "static";
        } | {
            /** @enum {string} */
            type: "dynamic";
        } | {
            /** @description Connection hints for the user to connect to the challenge */
            connection_hints?: components["schemas"]["ConnectionHint"][] | null;
            /** @description Containers that should be created in the challenge Pod */
            containers: components["schemas"]["ChallengeContainer"][];
            /** @enum {string} */
            type: "container";
        };
        ConnectionHint: {
            password?: string | null;
            /** Format: int32 */
            port?: number | null;
            /** @enum {string} */
            type: "ssh";
            username?: string | null;
        } | {
            /** Format: int32 */
            port?: number | null;
            /** @enum {string} */
            type: "http";
        } | {
            /** Format: int32 */
            port?: number | null;
            /** @enum {string} */
            type: "tcp";
        } | {
            /** Format: int32 */
            port?: number | null;
            /** @enum {string} */
            type: "udp";
        } | {
            /** Format: int32 */
            port?: number | null;
            protocol: string;
            /** @enum {string} */
            type: "other";
        };
        Course: components["schemas"]["CourseMetadata_CourseItem_String"] & {
            _id: string;
            /** @description Commit hash of the repository the course was imported from */
            ref: string;
        };
        /** @enum {string} */
        CourseDifficulty: "beginner" | "intermediate" | "advanced";
        /** @enum {string} */
        CourseItemType: "lesson" | "challenge";
        /** @description Metadata for a course
         *
         *     # Generics:
         *
         *     - `Item`: The type used to store individual course item */
        CourseMetadata_CourseItem_String: {
            /** @description A short description of the course */
            description: string;
            /** @description The difficulty level of the course */
            difficulty: components["schemas"]["CourseDifficulty"];
            /** @description Items included in the course (order matters) */
            items: ({
                lesson: string;
            } | {
                challenge: string;
            })[];
            /** @description A short unique name for the course */
            name: string;
            /** @description A list of learning objectives for the course */
            objectives?: string[] | null;
            /** @description A list of course slugs that are prerequisites for this course */
            prerequisites?: string[] | null;
            /** @description A URL-friendly unique identifier for the course */
            slug: string;
            /** @description Tags associated with the course */
            tags?: string[] | null;
        };
        /** @description Metadata for a course
         *
         *     # Generics:
         *
         *     - `Item`: The type used to store individual course item */
        CourseMetadata_DetailedCourseItem: {
            /** @description A short description of the course */
            description: string;
            /** @description The difficulty level of the course */
            difficulty: components["schemas"]["CourseDifficulty"];
            /** @description Items included in the course (order matters) */
            items: ((components["schemas"]["DetailedCourseLesson"] & {
                /** @enum {string} */
                type: "lesson";
            }) | (components["schemas"]["DetailedCourseChallenge"] & {
                /** @enum {string} */
                type: "challenge";
            }))[];
            /** @description A short unique name for the course */
            name: string;
            /** @description A list of learning objectives for the course */
            objectives?: string[] | null;
            /** @description A list of course slugs that are prerequisites for this course */
            prerequisites?: string[] | null;
            /** @description A URL-friendly unique identifier for the course */
            slug: string;
            /** @description Tags associated with the course */
            tags?: string[] | null;
        };
        /** @example {
         *       "success": true,
         *       "id": "60c72b2f9b1d8c001c8e4f5a"
         *     } */
        CreateSuccess: {
            id: string;
            success: boolean;
        };
        DetailedCourse: components["schemas"]["CourseMetadata_DetailedCourseItem"] & {
            _id: string;
            ref: string;
        };
        DetailedCourseChallenge: {
            _id: string;
            name: string;
            slug: string;
        };
        DetailedCourseLesson: {
            _id: string;
            name: string;
            slug: string;
        };
        FlagSubmissionRequest: {
            flag: string;
        };
        FlagSubmissionResult: {
            correct: boolean;
        };
        GenericError: {
            error: string;
        };
        /** @description Further information can be obtained from Socket.IO connection */
        KubernetesActionResult: {
            success: boolean;
        };
        LastItem: {
            slug: string;
            type: components["schemas"]["CourseItemType"];
        };
        Lesson: components["schemas"]["LessonMetadata"] & {
            _id: string;
            attachments: string[];
            content: string;
            course_slug: string;
        };
        LessonMetadata: {
            /** @description A short name for the lesson */
            name: string;
            /** @description A URL-friendly unique identifier for the lesson */
            slug: string;
        };
        /** @example {
         *       "error": "Not Found"
         *     } */
        NotFoundError: {
            error: string;
        };
        /** @example {
         *       "error": "Unauthorized"
         *     } */
        UnauthorizedError: {
            error: string;
        };
        UpdateChallengeRequest: {
            metadata: components["schemas"]["ChallengeMetadata"];
            ref: string;
        };
        UpdateCourseRequest: {
            metadata: components["schemas"]["CourseMetadata_CourseItem_String"];
            ref: string;
        };
        UpdateLessonRequest: {
            content: string;
            metadata: components["schemas"]["LessonMetadata"];
        };
        User: {
            _id: string;
            email: string;
            name: string;
            subject: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    check_system_auth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthCheckSuccess"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    get_challenge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Challenge slug */
                challenge_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Challenge"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description Challenge not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    update_challenge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Challenge slug */
                challenge_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChallengeRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSuccess"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    extend_challenge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Challenge slug */
                challenge_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KubernetesActionResult"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            /** @description Challenge not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    start_challenge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Challenge slug */
                challenge_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KubernetesActionResult"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            /** @description Challenge not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    stop_challenge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Challenge slug */
                challenge_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KubernetesActionResult"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description Challenge not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    submit_flag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Challenge slug */
                challenge_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlagSubmissionRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlagSubmissionResult"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description Challenge not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    get_courses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    get_course: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Course slug */
                course_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedCourse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description Course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    update_course: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Course slug */
                course_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCourseRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSuccess"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    save_last: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Course slug */
                course_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LastItem"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description Course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    get_course_lesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Course slug */
                course_slug: string;
                /** @description Lesson slug */
                lesson_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description Course or lesson not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    update_course_lesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Course slug */
                course_slug: string;
                /** @description Lesson slug */
                lesson_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLessonRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSuccess"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    log_in: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    get_challenge_schema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    get_contest_schema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    get_contest_batch_schema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    get_course_schema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    get_lesson_schema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    get_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    websocket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
}
