/*
 * headscale/v1/headscale.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HeadscaleServiceSetApprovedRoutesBody {
    #[serde(rename = "routes", skip_serializing_if = "Option::is_none")]
    pub routes: Option<Vec<String>>,
}

impl HeadscaleServiceSetApprovedRoutesBody {
    pub fn new() -> HeadscaleServiceSetApprovedRoutesBody {
        HeadscaleServiceSetApprovedRoutesBody {
            routes: None,
        }
    }
}

