/*
 * headscale/v1/headscale.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1BackfillNodeIpsResponse {
    #[serde(rename = "changes", skip_serializing_if = "Option::is_none")]
    pub changes: Option<Vec<String>>,
}

impl V1BackfillNodeIpsResponse {
    pub fn new() -> V1BackfillNodeIpsResponse {
        V1BackfillNodeIpsResponse {
            changes: None,
        }
    }
}

