/*
 * headscale/v1/headscale.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1CreateApiKeyResponse {
    #[serde(rename = "apiKey", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
}

impl V1CreateApiKeyResponse {
    pub fn new() -> V1CreateApiKeyResponse {
        V1CreateApiKeyResponse {
            api_key: None,
        }
    }
}

