/*
 * headscale/v1/headscale.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1CreatePreAuthKeyResponse {
    #[serde(rename = "preAuthKey", skip_serializing_if = "Option::is_none")]
    pub pre_auth_key: Option<Box<models::V1PreAuthKey>>,
}

impl V1CreatePreAuthKeyResponse {
    pub fn new() -> V1CreatePreAuthKeyResponse {
        V1CreatePreAuthKeyResponse {
            pre_auth_key: None,
        }
    }
}

