/*
 * headscale/v1/headscale.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1CreatePreAuthKeyRequest {
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
    #[serde(rename = "reusable", skip_serializing_if = "Option::is_none")]
    pub reusable: Option<bool>,
    #[serde(rename = "ephemeral", skip_serializing_if = "Option::is_none")]
    pub ephemeral: Option<bool>,
    #[serde(rename = "expiration", skip_serializing_if = "Option::is_none")]
    pub expiration: Option<String>,
    #[serde(rename = "aclTags", skip_serializing_if = "Option::is_none")]
    pub acl_tags: Option<Vec<String>>,
}

impl V1CreatePreAuthKeyRequest {
    pub fn new() -> V1CreatePreAuthKeyRequest {
        V1CreatePreAuthKeyRequest {
            user: None,
            reusable: None,
            ephemeral: None,
            expiration: None,
            acl_tags: None,
        }
    }
}

