/*
 * headscale/v1/headscale.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ListPreAuthKeysResponse {
    #[serde(rename = "preAuthKeys", skip_serializing_if = "Option::is_none")]
    pub pre_auth_keys: Option<Vec<models::V1PreAuthKey>>,
}

impl V1ListPreAuthKeysResponse {
    pub fn new() -> V1ListPreAuthKeysResponse {
        V1ListPreAuthKeysResponse {
            pre_auth_keys: None,
        }
    }
}

