/*
 * headscale/v1/headscale.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ListApiKeysResponse {
    #[serde(rename = "apiKeys", skip_serializing_if = "Option::is_none")]
    pub api_keys: Option<Vec<models::V1ApiKey>>,
}

impl V1ListApiKeysResponse {
    pub fn new() -> V1ListApiKeysResponse {
        V1ListApiKeysResponse {
            api_keys: None,
        }
    }
}

