/*
 * headscale/v1/headscale.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MoveNodeResponse {
    #[serde(rename = "node", skip_serializing_if = "Option::is_none")]
    pub node: Option<Box<models::V1Node>>,
}

impl V1MoveNodeResponse {
    pub fn new() -> V1MoveNodeResponse {
        V1MoveNodeResponse {
            node: None,
        }
    }
}

