/*
 * headscale/v1/headscale.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1Node {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "machineKey", skip_serializing_if = "Option::is_none")]
    pub machine_key: Option<String>,
    #[serde(rename = "nodeKey", skip_serializing_if = "Option::is_none")]
    pub node_key: Option<String>,
    #[serde(rename = "discoKey", skip_serializing_if = "Option::is_none")]
    pub disco_key: Option<String>,
    #[serde(rename = "ipAddresses", skip_serializing_if = "Option::is_none")]
    pub ip_addresses: Option<Vec<String>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::V1User>>,
    #[serde(rename = "lastSeen", skip_serializing_if = "Option::is_none")]
    pub last_seen: Option<String>,
    #[serde(rename = "expiry", skip_serializing_if = "Option::is_none")]
    pub expiry: Option<String>,
    #[serde(rename = "preAuthKey", skip_serializing_if = "Option::is_none")]
    pub pre_auth_key: Option<Box<models::V1PreAuthKey>>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "registerMethod", skip_serializing_if = "Option::is_none")]
    pub register_method: Option<models::V1RegisterMethod>,
    #[serde(rename = "forcedTags", skip_serializing_if = "Option::is_none")]
    pub forced_tags: Option<Vec<String>>,
    #[serde(rename = "invalidTags", skip_serializing_if = "Option::is_none")]
    pub invalid_tags: Option<Vec<String>>,
    #[serde(rename = "validTags", skip_serializing_if = "Option::is_none")]
    pub valid_tags: Option<Vec<String>>,
    #[serde(rename = "givenName", skip_serializing_if = "Option::is_none")]
    pub given_name: Option<String>,
    #[serde(rename = "online", skip_serializing_if = "Option::is_none")]
    pub online: Option<bool>,
    #[serde(rename = "approvedRoutes", skip_serializing_if = "Option::is_none")]
    pub approved_routes: Option<Vec<String>>,
    #[serde(rename = "availableRoutes", skip_serializing_if = "Option::is_none")]
    pub available_routes: Option<Vec<String>>,
    #[serde(rename = "subnetRoutes", skip_serializing_if = "Option::is_none")]
    pub subnet_routes: Option<Vec<String>>,
}

impl V1Node {
    pub fn new() -> V1Node {
        V1Node {
            id: None,
            machine_key: None,
            node_key: None,
            disco_key: None,
            ip_addresses: None,
            name: None,
            user: None,
            last_seen: None,
            expiry: None,
            pre_auth_key: None,
            created_at: None,
            register_method: None,
            forced_tags: None,
            invalid_tags: None,
            valid_tags: None,
            given_name: None,
            online: None,
            approved_routes: None,
            available_routes: None,
            subnet_routes: None,
        }
    }
}

