/*
 * headscale/v1/headscale.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PreAuthKey {
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::V1User>>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "reusable", skip_serializing_if = "Option::is_none")]
    pub reusable: Option<bool>,
    #[serde(rename = "ephemeral", skip_serializing_if = "Option::is_none")]
    pub ephemeral: Option<bool>,
    #[serde(rename = "used", skip_serializing_if = "Option::is_none")]
    pub used: Option<bool>,
    #[serde(rename = "expiration", skip_serializing_if = "Option::is_none")]
    pub expiration: Option<String>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "aclTags", skip_serializing_if = "Option::is_none")]
    pub acl_tags: Option<Vec<String>>,
}

impl V1PreAuthKey {
    pub fn new() -> V1PreAuthKey {
        V1PreAuthKey {
            user: None,
            id: None,
            key: None,
            reusable: None,
            ephemeral: None,
            used: None,
            expiration: None,
            created_at: None,
            acl_tags: None,
        }
    }
}

