/*
 * headscale/v1/headscale.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum V1RegisterMethod {
    #[serde(rename = "REGISTER_METHOD_UNSPECIFIED")]
    RegisterMethodUnspecified,
    #[serde(rename = "REGISTER_METHOD_AUTH_KEY")]
    RegisterMethodAuthKey,
    #[serde(rename = "REGISTER_METHOD_CLI")]
    RegisterMethodCli,
    #[serde(rename = "REGISTER_METHOD_OIDC")]
    RegisterMethodOidc,

}

impl std::fmt::Display for V1RegisterMethod {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RegisterMethodUnspecified => write!(f, "REGISTER_METHOD_UNSPECIFIED"),
            Self::RegisterMethodAuthKey => write!(f, "REGISTER_METHOD_AUTH_KEY"),
            Self::RegisterMethodCli => write!(f, "REGISTER_METHOD_CLI"),
            Self::RegisterMethodOidc => write!(f, "REGISTER_METHOD_OIDC"),
        }
    }
}

impl Default for V1RegisterMethod {
    fn default() -> V1RegisterMethod {
        Self::RegisterMethodUnspecified
    }
}

