/*
 * headscale/v1/headscale.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1SetPolicyRequest {
    #[serde(rename = "policy", skip_serializing_if = "Option::is_none")]
    pub policy: Option<String>,
}

impl V1SetPolicyRequest {
    pub fn new() -> V1SetPolicyRequest {
        V1SetPolicyRequest {
            policy: None,
        }
    }
}

